/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KundenPanel.java
 *
 * Created on Mar 3, 2011, 11:14:24 PM
 */
package GUI;

import DAO.DAOFactory;
import DAO.KundenDAO;
import Entities.Kunde;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author georg
 */
public class KundenPanel extends javax.swing.JPanel {
    dataModel dataModel = new dataModel();
    private ArrayList<Kunde> kunden;
    
    private class dataModel extends AbstractTableModel {
        public dataModel() {
            DAOFactory df = DAOFactory.getDAOFactory(DAOFactory.DERBY);
            KundenDAO kd = df.getKundenDAO();
            kunden = kd.getKunden();
        }

        public int getRowCount() {
            return kunden.size();
        }

        public int getColumnCount() {
            return 2;
        }

        public Object getValueAt(int rowIndex, int columnIndex) {
            Kunde k = kunden.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return k.getID() == -1 ? "neu" : k.getID();
                case 1:
                    return k.getName();
                default:
                    return 0;
            }
        }

        @Override
        public String getColumnName(int column) {
            switch (column) {
                case 0:
                    return "ID";
                case 1:
                    return "Name";
                default:
                    return "nooooooo!";
            }
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            if(columnIndex == 0)
                return false;
            return true;
        }
        
        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex){
            Kunde k = kunden.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    break;
                case 1:
                    k.setName((String) aValue);
                    break;
                default:
                    break;
            }
        }

        public void addRow(){
            int rowIndex = kunden.size();
            kunden.add(new Kunde(-1, ""));
            fireTableChanged(new TableModelEvent(this, rowIndex, rowIndex, -1, TableModelEvent.INSERT));
        }
        
    }

    /** Creates new form KundenPanel */
    public KundenPanel() {
        initComponents();
        DefaultTableModel x;

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnUndo = new javax.swing.JButton();
        jBtnSave = new javax.swing.JButton();
        jBtnDelete = new javax.swing.JButton();
        jBtnAdd = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(dataModel);
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPane1, gridBagConstraints);

        jBtnUndo.setIcon(new javax.swing.ImageIcon("/home/georg/NetBeansProjects/SWE_2/src/GUI/Undo.png")); // NOI18N
        jBtnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUndoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jBtnUndo, gridBagConstraints);

        jBtnSave.setIcon(new javax.swing.ImageIcon("/home/georg/NetBeansProjects/SWE_2/src/GUI/Save.png")); // NOI18N
        jBtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSaveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jBtnSave, gridBagConstraints);

        jBtnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Delete-icon.png"))); // NOI18N
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jBtnDelete, gridBagConstraints);

        jBtnAdd.setIcon(new javax.swing.ImageIcon("/home/georg/NetBeansProjects/SWE_2/src/GUI/Add.png")); // NOI18N
        jBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        add(jBtnAdd, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaveActionPerformed
        DAOFactory df = DAOFactory.getDAOFactory(DAOFactory.DERBY);
        KundenDAO kd = df.getKundenDAO();
        
        JOptionPane.showMessageDialog(this, "Updated " + kd.updateKunden(kunden)  + " Rows");

        dataModel = new dataModel();
        jTable1.setModel(dataModel);
    }//GEN-LAST:event_jBtnSaveActionPerformed

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
        DAOFactory df = DAOFactory.getDAOFactory(DAOFactory.DERBY);
        KundenDAO kd = df.getKundenDAO();

        int rowIndex = jTable1.getSelectedRow();
        if(rowIndex != -1){
            kd.deleteKunde(kunden.get(rowIndex));
            kunden.remove(rowIndex);
        }

        jTable1.updateUI();
        jTable1.repaint();
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUndoActionPerformed
        dataModel = new dataModel();
        jTable1.setModel(dataModel);
    }//GEN-LAST:event_jBtnUndoActionPerformed

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAddActionPerformed
        dataModel.addRow();
    }//GEN-LAST:event_jBtnAddActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnSave;
    private javax.swing.JButton jBtnUndo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
